server:
  port: 8001

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/replanet
    username: root
    password: 74320305

#jwt:
#  key: dkjkla23djflka123djflk23420394rjglasdkgljdl
#  time: 86400000

